### ISSUE TITLE
Example config.json

### ISSUE THREAD

**Issue by dcaccount** [spobel/homebridge-gpio-services#3]
Hello,

Thanks for your plugin. First of all could you please provide an example of a config.json file for a contact sensor?

Then could you please advise if your plugin works with latest node.js and if it does rely on wiringPi library?

Thanks!
Dan

**Comment by toshibochan** [comment]
@dcaccount  Use homebridge-gpio-devices

**Comment by dcaccount** [comment]
homebridge-gpio-devices relies on wiringPi that has been deprecated

**Comment by toshibochan** [comment]
I see. Look config.json in this repository have contact sensor example

**Comment by dcaccount** [comment]
Have you tried this plugin, does it work perfectly?

**Comment by toshibochan** [comment]
I didn’t try. I use homebridge-gpio-devices

**Comment by spobel** [comment]
Hi, as you can see in package.json, this project depends on [onoff](https://www.npmjs.com/package/onoff) library.
This plugin works with latest nodejs LTS 12.16.3.

There is an example config.json in this project with all different accessories.
Thanks for using.
