### ISSUE TITLE
excuse me for offtopic - it is just a question concerning your homebridge innogy plugin

### ISSUE THREAD

**Issue by fpPierre** [spobel/homebridge-gpio-services#4]
Dear Sebastian,

on npmjs I and within the homebridge plugin repo I found your innogy plugin.
I´m curious whether this is operational and can be used.
Maybe you can support me with some information, a short how/to or doc.

P.S. Gerne können wir uns auch auf Deutsch austauschen

Gruß / Cheers,
Pierre

**Comment by spobel** [comment]
Das Projekt wurde gelöscht.
